### PR TITLE
gyro and accel scale wrong: should be specified in milli-unit per bit!

### PR DESCRIPTION
**Pull request by gauteh**
possibly also wrong in Adafruit driver: https://github.com/adafruit/Adafruit_LSM6DS/issues/40

this gives better values for acceleration when using other scales than
2.

Please take a good look on this one, not sure if it is correct.

### CODE REVIEW

**Comment by gauteh** [comment]
Basically it seems like I introduced this error here: 23dbc52 ! However, the gyro values are still wrong in the same way as the adafruit driver is. If that is the case.

**Comment by gauteh** [comment]
I've asked on the ST forum: https://community.st.com/t5/mems-sensors/ism330dhcx-gyro-range-in-driver-calculation-does-not-make-sense/m-p/605528#M21746

**Comment by gauteh** [comment]
I think it is correct now. The scaling for the gyro is given in the datasheet as mdps / LSP in table 2.

**Comment by gauteh** [comment]
I have made some more structural changes. These will make it easier to keep track of units, scaling and not mixing different value types.

**Comment by sousandrei** [comment]
@gauteh finally had time to look into this!

Tested it on my end and the values indeed look better with the fix, nice spot haha
I'll borrow your idea for the value types and add it to the magnetometer later

one thing, do you mind rewording the commits to adhere to the "conventional commits" convention?
then our versioning bot can pick up the changes and generate the changelog right away (not sure I can push to this branch to help)

otherwise, as soon as I merge I'll release the new version to crates.io!

**Comment by gauteh** [comment]
Nice, thanks. I think you can rebase+edit+amend the commits. Not sure how you want the text. What magnetometer? I need to add one to my project soon 😁

**Comment by sousandrei** [comment]
I don't have access to your repo, so I'll do a little duct tape on main, should be fine :D

**Comment by gauteh** [comment]
Thanks! I forgot to check the allow edits box! Sorry about that.

**Pull request merged**
