### PR TITLE
fifo: configure FIFO and read FIFO status.

### PR DESCRIPTION
**Pull request by gauteh**
You can test on host by doing `make host-test`. You have to add `embedded-hal-mock` as a dev-dependency, the stm crate doesn't resolve for me so I had to disable all the deps related to the example -- and thus it was a pain to add this new dep.

### CODE REVIEW

**Comment by gauteh** [comment]
The FIFO pop function will be called very often. At the moment the scale value is retrieved every time, but from the local cache. I don't know if this is going to be a problem or if this is compiled away.

**Comment by gauteh** [comment]
I have tested this some more and it seems to work pretty well. It is not necessary to have a regular `ODR` configured for gyro or accel for the FIFO to fill up, you just have to set the respective BDRs. Like you see there are a couple of panics introduced, which can either be replaced by the necessary code or just some `Other` type maybe.

**Review by sousandrei — APPROVED** [review]
Finally had time to test this on host and on board
Amazing work!
Did even a better job at tests than me haha

**Comment by gauteh** [comment]
Great! Thanks :)

**Pull request merged**
